### ISSUE TITLE
cluster down spec requirements 

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/troubleshoot-specs#35]
By following the steps:

- Install `curl https://kurl.sh/latest | sudo bash` in an environment with all pre-requirements 
- Then, follow the steps:  https://community.replicated.com/t/kurl-how-can-i-generate-a-support-bundle-when-my-kubernetes-cluster-is-down/911 

We check the following errors:

<img width="1420" alt="Screenshot 2023-01-18 at 10 06 22" src="https://user-images.githubusercontent.com/7708031/213160953-4ac7a9e2-927d-4990-b0c6-e08a298660fb.png">

For default installs those does not seems required at all. For example, docker is deprecated and kurl installs used containerd by default. So, we might want to do the check with the containerd and no longer raise an error if docker is not found. 

c/c @danj-replicated @banjoh @edgarlanting

**Comment by camilamacedo86** [comment]
Look the issue : https://github.com/replicatedhq/troubleshoot/issues/659 it might help us to sort out the spec.

**Comment by xavpaice** [comment]
These collectors are enabled in the default bundle as a capture-all type step - the errors in running them are perfectly valid (they can't run).  I think that the purpose of this spec is to have a "try to grab everything, even if it can't be collected" so that we can point folks at the spec when we have no idea about their environment.

There's structural changes needed in Troubleshoot - e.g. replace the run collector with a "collect container runtime" collector, but that's outside the scope of this project.

I'll close this one out for now.
